shorter/views/main.py
from collections import namedtuple

from flask import (
    Blueprint,
    abort,
    current_app,
    make_response,
    render_template,
    request,
)

from shorter.forms.short import ShortCreateForm, ShortDisplayForm
from shorter.models.short import Short
from shorter.start.environment import DELAY_DEF
from shorter.support import is_botagent

LINK = namedtuple("Link", ("source", "target"))
BLUEPRINT_MAIN = Blueprint("main", __name__)


@BLUEPRINT_MAIN.route(
    "/",
    methods=["GET", "POST"],
)
def index():
    link = None
    form = ShortCreateForm(
        target=request.args.get("target"),
        delay=request.args.get("delay", DELAY_DEF),
    )
    if form.validate_on_submit():
        obj = form.action()
        if obj:
            form = ShortDisplayForm(obj=obj)
            link = LINK(source=form.link.data, target=obj.target)

    return render_template(
        "index.html",
        title=current_app.config.get("TITLE"),
        form=form,
        link=link,
    )


@BLUEPRINT_MAIN.route("/<symbol:symb>")
def short(symb):
    if is_botagent(request.user_agent):
        abort(403)

    item = Short.by_symbol_active(symb)
    if not item:
        abort(404)

    item.increase_visit()
    resp = make_response(
        render_template(
            "short.html",
            title=item.symbol,
            short=item,
        )
    )

    resp.headers.add("X-Robots-Tag", "noindex, nofollow")
    return resp

shorter/views/plus.py
from flask import (
    Blueprint,
    abort,
    current_app,
    redirect,
    render_template,
    request,
)

from shorter.forms.short import ShortFindForm
from shorter.models.short import Short
from shorter.support import BLOCKLIST

BLUEPRINT_PLUS = Blueprint("plus", __name__, url_prefix="/plus")


@BLUEPRINT_PLUS.route("/")
def index():
    form = ShortFindForm(
        term=request.args.get("q"),
    )

    return render_template(
        "plus/index.html",
        title="Plus",
        form=form,
    )


@BLUEPRINT_PLUS.route(
    "/show/<string:field>/<any(asc,desc):sort>/<int:page>",
    methods=["POST", "GET"],
)
@BLUEPRINT_PLUS.route(
    "/show/<string:field>/<int:page>",
    methods=["POST", "GET"],
)
@BLUEPRINT_PLUS.route(
    "/show/<int:page>",
    methods=["POST", "GET"],
)
@BLUEPRINT_PLUS.route(
    "/show",
    methods=["POST", "GET"],
)
def show(page=None, field=None, sort=None):
    term = request.args.get("q", None)
    form = ShortFindForm(term=term)
    if form.validate_on_submit():
        target = form.action()
        if target:
            return redirect(target)

    query = (
        Short.searched(term, field=field, rev=sort == "desc")
        if term is not None
        else Short.ordered(field=field, rev=sort == "desc")
    )
    if not query:
        abort(404)

    return render_template(
        "plus/show.html",
        title="Show",
        form=form,
        elements=query.paginate(
            page=page, per_page=current_app.config["PAGINATION"]
        ),
    )


@BLUEPRINT_PLUS.route("/block/<string:field>/<any(asc,desc):sort>/<int:page>")
@BLUEPRINT_PLUS.route("/block/<string:field>/<int:page>")
@BLUEPRINT_PLUS.route("/block/<int:page>")
@BLUEPRINT_PLUS.route("/block")
def block(page=None, field=None, sort=None):
    query = Short.blocked(BLOCKLIST, field=field, rev=sort == "desc")
    if not query:
        abort(404)

    return render_template(
        "plus/show.html",
        title="Blocked",
        elements=query.paginate(
            page=page, per_page=current_app.config["PAGINATION"]
        ),
    )

shorter/templates/plus/_find.html
{% macro findbox(form) %}
<form action="{{ url_for('plus.show') }}" method="post">
  {{ form.csrf_token() if form.csrf_token }}

  <div class="field has-addons">
    <div class="control is-expanded">
      {{ form.term(
        class='input',
        placeholder='Suchen',
        title='Der Suchbegriff'
      ) }}
    </div>
    <div class="control">
      {{ form.send(
        class='button is-link',
        value='Finden',
        title='Wer suchet der findet!'
      ) }}
    </div>
  </div>
</form>
{% endmacro %}

shorter/templates/plus/_func.html
{% macro pagination(pobj) %}
  {% macro page_url(page) %}
    {% with args = request.view_args %}
    {% set _ = args.update(page=page) %}
    {% set _ = args.update(**request.args) %}
      {{ url_for(request.endpoint, **args) }}
    {% endwith %}
  {% endmacro %}

  <nav class="pagination is-centered">
    {% if pobj.page != 1 %}
      <a
        class="pagination-previous"
        href="{{ page_url(pobj.prev_num) }}"
      >Previous</a>
    {% endif %}
    {% if pobj.pages and pobj.page != pobj.pages %}
      <a
        class="pagination-next"
        href="{{ page_url(pobj.next_num) }}"
      >Next</a>
    {% endif %}
    <ul class="pagination-list">
      {% if pobj.page != 1 %}
        <li><a
          class="pagination-link"
          href="{{ page_url(1) }}"
        >1</a></li>
      {% endif %}
      {% if pobj.has_prev and pobj.prev_num != 1 %}
        {% if pobj.prev_num == 3 %}
          <li><a
            class="pagination-link"
            href="{{ page_url(2) }}"
          >2</a></li>
        {% elif pobj.prev_num > 2 %}
          <li>
            <span class="pagination-ellipsis">&hellip;</span>
          </li>
        {% endif %}
        <li><a
          class="pagination-link"
          href="{{ page_url(pobj.prev_num) }}"
        >{{ pobj.prev_num }}</a></li>
      {% endif %}
      <li><a
        class="pagination-link is-current"
        href="{{ page_url(pobj.page) }}"
      >{{ pobj.page }}</a></li>
      {% if pobj.has_next and pobj.next_num != pobj.pages %}
        <li><a
          class="pagination-link"
          href="{{ page_url(pobj.next_num) }}"
        >{{ pobj.next_num }}</a></li>
        {% if (pobj.pages - pobj.next_num) > 2 %}
          <li>
            <span class="pagination-ellipsis">&hellip;</span>
          </li>
        {% elif (pobj.pages - pobj.next_num) == 2 %}
          <li><a
            class="pagination-link"
            href="{{ page_url(pobj.next_num + 1) }}"
          >{{ pobj.next_num + 1 }}</a></li>
        {% endif %}
      {% endif %}
      {% if pobj.pages and pobj.page != 0 and pobj.page != pobj.pages %}
        <li><a
          class="pagination-link"
          href="{{ page_url(pobj.pages) }}"
        >{{ pobj.pages }}</a></li>
      {% endif %}
    </ul>
  </nav>
{% endmacro %}

shorter/templates/plus/index.html
{% extends '_base.html' %}
{% from 'plus/_find.html' import findbox %}

{% block content %}
<div class="columns">
  <div class="column is-8-desktop is-offset-2-desktop">
    <div class="content">
      <h2>Plus</h2>
      <div>
        <ul>
          <li><a href="{{ url_for('plus.show') }}">Tabelle</a></li>
          <li><a href="{{ url_for('plus.block') }}">Blockiert</a></li>
        </ul>
      </div>
    </div>
    {% if form %}
    <div class="content">
      <h2>Suchen</h2>
      <div>
        {{ findbox(form) }}
      </div>
    </div>
    {% endif %}
  </div>
</div>
{% endblock %}

shorter/templates/plus/show.html
{% extends '_base.html' %}
{% from 'plus/_find.html' import findbox %}
{% from 'plus/_func.html' import pagination %}

{% macro heading() %}
  {% macro order_urls(field) %}
    <a href="{{ url_for(request.endpoint, page=1, field=field, sort='asc', **request.args) }}">&#8593;</a>
    <a href="{{ url_for(request.endpoint, page=1, field=field, sort='desc', **request.args) }}">&#8595;</a>
  {% endmacro %}

<tr>
  <th>
    <abbr title="Primary ID">Prime</abbr>
    {{ order_urls('prime') }}
  </th>
  <th>
    Symbol
    {{ order_urls('symbol') }}
  </th>
  <th>
    Target
    {{ order_urls('target') }}
  </th>
  <th>
    <abbr title="Forward delay in seconds">Delay</abbr>
    {{ order_urls('delay') }}
  </th>
  <th>
    Active
    {{ order_urls('active') }}
  </th>
  <th>
    <abbr title="Visit counter">Visited</abbr>
    {{ order_urls('visited') }}
  </th>
  <th>
    <abbr title="Creation Date (UTC)">Created</abbr>
    {{ order_urls('created') }}
  </th>
</tr>
{% endmacro %}

{% macro element(item) %}
<tr>
  <td>{{ item.prime }}</td>
  <td><a href="{{ url_for('main.short', symb=item.symbol) }}">{{ item.symbol }}</a></td>
  <td>{{ item.target|urlize(23, target='_blank', rel='nofollow') }}</td>
  <td>{{ item.delay }}</td>
  <td>{{ ('&#10003;' if item.active else '&#10005;')|safe }}</td>
  <td>{{ item.visited }}</td>
  <td>{{ item.created }}</td>
</tr>
{% endmacro %}


{% block content %}
<div class="columns">
  <div class="column is-fullwidth">
    <div class="content">
      <h2>{{ title }}</h2>
      {% if form %}
      <div class="content">
        {{ findbox(form) }}
      </div>
      {% endif %}
      {% if elements and elements.items %}
      <div class="table-container">
        <table class="table is-fullwidth">
          <thead>
            {{ heading() }}
          </thead>
          <tbody>
            {% for item in elements.items %}
              {{ element(item) }}
            {% endfor %}
          </tbody>
          <tfoot>
            {{ heading() }}
          </tfoot>
        </table>
      </div>
      {% else  %}
      <div>Nothing there!</div>
      {% endif %}
    </div>
  </div>
</div>
{% if elements and elements.items %}
<div class="columns">
  <div class="column is-fullwidth">
    {{ pagination(elements) }}
  </div>
</div>
{% endif %}
{% endblock %}