shorter/views/main.py
from collections import namedtuple

from flask import (
    Blueprint,
    abort,
    current_app,
    make_response,
    render_template,
    request,
)

from shorter.forms.short import ShortCreateForm, ShortDisplayForm
from shorter.models.short import Short
from shorter.start.environment import DELAY_DEF
from shorter.support import is_botagent

LINK = namedtuple("Link", ("source", "target"))
BLUEPRINT_MAIN = Blueprint("main", __name__)


@BLUEPRINT_MAIN.route(
    "/",
    methods=["GET", "POST"],
)
def index():
    link = None
    form = ShortCreateForm(
        target=request.args.get("target"),
        delay=request.args.get("delay", DELAY_DEF),
    )
    if form.validate_on_submit():
        obj = form.action()
        if obj:
            form = ShortDisplayForm(obj=obj)
            link = LINK(source=form.link.data, target=obj.target)

    return render_template(
        "index.html",
        title=current_app.config.get("TITLE"),
        form=form,
        link=link,
    )


@BLUEPRINT_MAIN.route("/<symbol:symb>")
def short(symb):
    if is_botagent(request.user_agent):
        abort(403)

    item = Short.by_symbol_active(symb)
    if not item:
        abort(404)

    item.increase_visit()
    resp = make_response(
        render_template(
            "short.html",
            title=item.symbol,
            short=item,
        )
    )

    resp.headers.add("X-Robots-Tag", "noindex, nofollow")
    return resp

shorter/templates/page/_page.html
{% extends '_base.html' %}
{% from '_code.html' import logo %}

{% block content %}
<div class="columns">
  <div class="column is-one-third">
    <div class="content">
{{ logo(href=url_for('main.index')) }}
    </div>
  </div>
  <div class="column is-two-thirds">
    <div class="content">
{% block page_content %}{% endblock %}
    </div>
  </div>
</div>
{% endblock %}

shorter/templates/page/details.html
{% set title = 'Details' %}
{% extends 'page/_page.html' %}

{% block page_content %}
<h1 class="title">Wer? Wie? Wo? Wann? Was?</h1>

<p>
  <a href="{{ url_for('main.index') }}">fckaf.de</a> ist ein
  <a href="https://de.wikipedia.org/wiki/Kurz-URL-Dienst">URL Shortener</a>.
  Fütter diesen mit einer Web-Adresse, und du erhälst eine Kurz-URL.
</p>
<p>
  Ein Aufruf der Kurz-URL leitet auf die ursprüngliche Web-Adresse weiter.
</p>

<h2 class="subtitle">Verlinkung</h2>
<p>
  <a href="{{ url_for('main.index') }}">fckaf.de</a> versucht die Platzierung
  der verlinkten Seiten in Suchmaschinen nicht zu beeinflussen.
</p>
<p>
  Hier kommen mehrere Techniken zum Einsatz:
</p>
<ul>
  <li>
    Der Kurz-Link wird mithilfe der
    <a href="https://de.wikipedia.org/wiki/Robots_Exclusion_Standard">
    robots.txt</a> blockiert, so dass Suchmaschinen diesen nicht verfolgen.
  </li>
  <li>
    Die Ursprüngliche Seite wird nur mithilfe des
    <a href="https://de.wikipedia.org/wiki/Nofollow">nofollow</a>
    Attributs verlinkt.
  </li>
  <li>
    Sollte dennoch eine Suchmaschine vorbei kommen, wird versucht dies zu
    erkennen, und dann wird mit dem
    <a href="https://de.wikipedia.org/wiki/HTTP-Statuscode#code403">
    HTTP Statuscode 403</a> (Forbidden) geantwortet.
  </li>
  <li>
    Die eigentliche Weiterleitung geschieht mithilfe von JavaScript, um
    eine Übertragung des
    <a href="https://de.wikipedia.org/wiki/Referrer">Referrers</a>
    zu verhindern.
  </li>
</ul>

<h2 class="subtitle">Bookmarklet</h2>
<p>
  Es gibt auch ein
  <a href="https://de.wikipedia.org/wiki/Bookmarklet">Bookmarklet</a>.
  Einfach den Link unten in die Lesezeichenleiste ziehen,
  und schon kann man damit schnell und einfach Kurz-URLs erzeugen!
</p>
<div class="has-text-centered">
  <cite>
    <a href="{{ bookmarklet() }}">Auf fckaf.de kürzen!</a>
  </cite>
</div>
{% endblock %}

shorter/templates/page/imprint.html
{% set title = 'Impressum' %}
{% extends 'page/_page.html' %}

{% block page_content %}
<h1 class="title">{{ title }}</h1>

<p>
  fckaf.de &incare;
  <br />
  Die PARTEI
  <br />
  Kopischstraße 10
  <br />
  10965 Berlin
</p>

<h2 class="subtitle">Kontakt</h2>
<p>
  E-Mail: fckafde &#64; die-partei.de
</p>

<h2 class="subtitle">EU-Streitschlichtung</h2>
<p>
  Die Europäische Kommission stellt eine Plattform zur
  Online-Streitbeilegung (OS) bereit:
  <a href="https://ec.europa.eu/consumers/odr" target="_blank" rel="noopener noreferrer">https://ec.europa.eu/consumers/odr</a>.
  <br />
  Unsere E-Mail-Adresse finden Sie oben im Impressum.
</p>


<h2 class="subtitle">Verbraucherstreitbeilegung/Universalschlichtungsstelle</h2>
<p>
  Wir sind nicht bereit oder verpflichtet, an Streitbeilegungsverfahren
  vor einer Verbraucherschlichtungsstelle teilzunehmen.
</p>

<p>
  Quelle:
  <a href="https://www.e-recht24.de">https://www.e-recht24.de</a>
</p>
{% endblock %}

shorter/templates/page/privacy.html
{% set title = 'Datenschutzerklärung' %}
{% extends 'page/_page.html' %}

{% block page_content %}
<h1 class="title">{{ title }}</h1>
<p>
  Wir nehmen den Schutz personenbezogener Daten sehr ernst.
</p>
<p>
  <strong>Wir speichern daher keine personenbezogenen Daten über Dich.</strong>
</p>

<p>
  Wir unterliegen den Bestimmungen der
  <a href="https://de.wikipedia.org/wiki/Datenschutz-Grundverordnung">
  Datenschutz-Grundverordnung</a> (DSGVO), des
  <a href="https://de.wikipedia.org/wiki/Bundesdatenschutzgesetz">
  Bundesdatenschutzgesetzes</a> (BDSG) und des
  <a href="https://de.wikipedia.org/wiki/Telemediengesetz">
  Telemediengesetzes</a> (TMG).
</p>

<p>
  Sollte Dir ein Verstoß auffallen, kontaktiere bitte unseren
  Datenschutzbeauftragten (siehe unten), damit wir den Verstoß umgehend
  durch technische und organisatorische Maßnahmen korrigieren können.
</p>

<h2 class="subtitle">Erhebung und Verarbeitung von Daten</h2>
<p>
  Personenbezogene Daten sind Informationen, die genutzt werden können,
  Deine Identität zu erfahren.
</p>

<p>
  Bei der Benutzung von <a href="{{ url_for('main.index') }}">fckaf.de</a>
  fallen solche Daten grundsätzlich an:
</p>
<ul>
  <li>
    <strong>Formulardaten:</strong> Wenn Du das Formular verwendest, um eine
    URL zu kürzen, lässt die URL in der Regel keinen direkten oder indirekten
    Rückschluss auf Deine Identität zu.
  </li>
  <li>
    <strong>Metadaten:</strong> Wenn Du die Webseite besuchst, übermittelt
    Dein Browser automatisch bestimmte Informationen und lässt damit
    gegebenenfalls einen indirekten Rückschluss auf Deine Identität zu.
  </li>
</ul>

<h2 class="subtitle">Formulardaten</h2>
<p>
  <a href="{{ url_for('main.index') }}">fckaf.de</a> bietet ein Formular an,
  mit dem Du eine Kurz-URL für eine bestehende Web-Adresse generieren kannst.
</p>

<p>
  Dazu fragen wir nur die URL, die Du kürzen möchtest, ab.
  Diese wird in einer Datenbank hinterlegt.
</p>

<h2 class="subtitle">Metadaten</h2>
<p>
  Wenn Du <a href="{{ url_for('main.index') }}">fckaf.de</a> besuchst,
  sendet Dein Browser automatisch verschiedene Metadaten:
</p>


<ul>
  <li>Browsertyp und -version</li>
  <li>Betriebssystem</li>
  <li>IP-Adresse des zugreifenden Endgeräts</li>
  <li>URL der besuchten Webseite</li>
  <li>URL der zuvor besuchten Webseite</li>
  <li>Zeitpunkt des Besuchs</li>
</ul>

<p>
  Wir speichern diese Daten aber nicht und verwenden sie auch nicht in
  anderer Form. Sollte <a href="{{ url_for('main.index') }}">fckaf.de</a>
  allerdings einmal zu Straftaten missbraucht und ein Ermittlungsverfahren
  eröffnet werden, können wir möglicherweise dazu verpflichtet werden, die
  Daten ungekürzt zu speichern und an Ermittlungsbehörden oder Privatpersonen
  auszuhändigen.
</p>

<h2 class="subtitle">Cookies</h2>
<p>
  <a href="{{ url_for('main.index') }}">fckaf.de</a> verwendet sogenante
  &bdquo;Cookies&ldquo;.
  Cookies sind kleine Textdateien, die auf Deinem Rechner abgelegt werden
  und die Dein Browser auf Deinem Endgerät speichert. Sie ermöglichen es
  insbesondere, mehrere einzelne Aufrufe einer Webseite einer Sitzung
  zuzuordnen und eingegebene Daten zwischenzuspeichern.
  Sie richten auf Deinem Rechner keinen Schaden an und enthalten keine Viren.
</p>

<p>
  Wenn Du keine Cookies annehmen willst, kannst Du dies durch eine
  Browser-Einstellung verhindern. Dadurch kannst Du allerdings das
  URL-Formular nicht nutzen.
</p>

<p>
  Es werden zwei Cookies verwendet:
</p>
<ol>
  <li>
    Der Cookie &bdquo;session&ldquo; wird ausschließlich verwendet,
    um zusammengehörige Anfragen zuzuordnen.
  </li>
  <li>
    Der Cookie &bdquo;{{ config.WTF_CSRF_FIELD_NAME|d('CSRF') }}&ldquo;
    wird ausschließlich verwendet, um sogenannte
    &bdquo;Cross-Site-Request-Forgery&ldquo;-Angriffe zu verhindern.
  </li>
</ol>

<h2 class="subtitle">Auskunftsrecht</h2>
<p>
  Du hast jederzeit das Recht auf Auskunft über
</p>
<ul>
  <li>die zu Deiner Person gespeicherten Daten,</li>
  <li>deren Herkunft und Empfänger sowie,</li>
  <li>den Zweck der Speicherung.</li>
</ul>

<p>
  Wende Dich dazu bitte an unseren Datenschutzbeauftragten (siehe unten).
</p>
<p>
  <strong>
    Bitte beachte jedoch, dass wir keine Daten zu Deiner Person speichern.
  </strong>
</p>

<h2 class="subtitle">Weitere Informationen</h2>
<p>
  Wenn Du Fragen hast, die Dir diese Datenschutzerklärung nicht beantworten
  konnte, wende Dich bitte an unseren Datenschutzbeauftragten:
</p>

<h3>Datenschutzbeauftragter</h3>
<p>
  datenschutz &#64; die-partei.de
</p>
{% endblock %}